apiVersion: v1
kind: Service
metadata:
  name: vllm-deepseek-r1-d-llama3-8b
spec:
  selector:
    app: vllm-deepseek-r1-d-llama3-8b
    model: deepseek-r1-d-llama3-8b
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30202  # External port (30000-32767 range)
  type: NodePort
