apiVersion: v1
kind: PersistentVolume
metadata:
  name: llm-pv
  labels:
    app: llm-service
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/tmp/postgres
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: llm-service
    component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: llm-pv
  storageClassName: standard
